services:
  postgres-db:
    image: postgres:17.5-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-product_catalog_prod}
      - POSTGRES_USER=${DATABASE_USERNAME:-prod_user}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-prod_password}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-prod_user} -d ${DATABASE_NAME:-product_catalog_prod}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
    # Security: Don't expose database port in production
    # ports:
    #   - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  product-catalog:
    image: ghcr.io/the-dave-stack/product-catalog:${IMAGE_TAG:-latest}
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod,docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${DATABASE_NAME:-product_catalog_prod}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME:-prod_user}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD:-prod_password}
      - JWT_SECRET=${JWT_SECRET:-changeme-production-secret-key-must-be-at-least-256-bits}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400}
      - JAVA_OPTS=-Xmx768m -Xms384m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
      # MCP Server Configuration - Production
      - MCP_SERVER_ENABLED=${MCP_SERVER_ENABLED:-true}
      - MCP_SERVER_NAME=${MCP_SERVER_NAME:-product-catalog-mcp-server-prod}
      - MCP_SERVER_VERSION=${MCP_SERVER_VERSION:-2.0.0-prod}
      - MCP_SSE_ENDPOINT=${MCP_SSE_ENDPOINT:-/sse}
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      # TODO: Use more comprehensive health check in the future (e.g., /actuator/health with proper business logic)
      # Current: Uses auth endpoint as it's always public and doesn't depend on database state
      # Previous (commented): curl with both /actuator/health AND /sse (latter requires auth)
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/auth/login"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 90s
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '1.0'
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

  # Optional: Reverse proxy for production
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      # Use production nginx config with enhanced security
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      # Fallback to standard config if nginx-prod.conf doesn't exist
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - product-catalog
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    profiles:
      - nginx

volumes:
  postgres_prod_data:
    driver: local

networks:
  app-network:
    driver: bridge