version: '3.8'
services:
  postgres-db:
    image: postgres:17.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=product_catalog
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
